[[Grpc]]
Name="etcd"
# BalancerName = "round_robin"
BalancerName = "swr"
Address = "etcd:///grpc:StockGrpc:v1:product"
# Address = "172.18.1.8:21000"
Block = false
DialTimeout = "1s"
ReadTimeout = "1s"
Direct = false
SlowThreshold = "1s"
Debug = false
EnableTraceInterceptor = false
EnableAidInterceptor   = false
EnableTimeoutInterceptor = false
EnableMetricInterceptor  = false
EnableAccessInterceptor  = true
AccessInterceptorLevel = "info"
Etcd = "etcd" # 代理的地址 proxyetcd.Name
# 节点名称
LinkNode = "grpc.common"
[[ProxyGrpc]]
Name = "grpc"
LinkNode = "grpc.common"