[[MongoDB]]
URI="mongodb://admin:admin@127.0.0.1:27017/stock?authSource=admin&authMechanism=SCRAM-SHA-256"
MaxConnIdleTime = 1
MaxPoolSize = 64
MinPoolSize = 10
# 开启指标采集
EnableMetric = true
# 开启链路追踪
EnableTrace = true
#节点名称
LinkNode = "mongodb.common"

[[ProxyMongoDB]]
Name = "mongodb"
LinkNode = "mongodb.common"