[[Redis]]
ClientType = "normal" #模式(normal => 单节点,cluster =>  集群,failover => 哨兵,ring => 分片)
Addr="127.0.0.1:6379"
Database = 10 #数据库序号
Password = "redis" #密码
PoolSize = 10
KeyPrefix = "Stock:"
EnableMetric = true # 开启指标采集
EnableTrace = true # 开启链路追踪
LinkNode = "redis.normal" # 节点名称

[[ProxyRedis]]
Name = "redis"
LinkNode = "redis.normal"

    # [redis.cluster]
    #     #集群
    #     ClientType = "cluster" #模式(normal => 单节点,cluster =>  集群,failover => 哨兵,ring => 分片)
    #     Hosts = ["172.18.1.5:6379","172.18.1.5:6379","172.18.1.5:6379"]
    #     Password = "" #密码
    #     PoolSize = 10
    #     KeyPrefix = ""
    #     # 开启指标采集
    #     EnableMetric = false
    #     # 开启链路追踪
    #     EnableTrace = false
    # [redis.failover]
    #     #哨兵
    #     ClientType = "failover" #模式(normal => 单节点,cluster =>  集群,failover => 哨兵,ring => 分片)
    #     MasterName = "master-name"
    #     Hosts = ["172.18.1.5:6379","172.18.1.5:6379","172.18.1.5:6379"]
    #     Password = "" #密码
    #     PoolSize = 10
    #     KeyPrefix = ""
    #     # 开启指标采集
    #     EnableMetric = false
    #     # 开启链路追踪
    #     EnableTrace = false
    # [redis.ring]
    #     #分片
    #     ClientType = "ring" #模式(normal => 单节点,cluster =>  集群,failover => 哨兵,ring => 分片)
    #     Password = "" #密码
    #     PoolSize = 10
    #     KeyPrefix = ""
    #     # 开启指标采集
    #     EnableMetric = false
    #     # 开启链路追踪
    #     EnableTrace = false
    #     [Addrs] #分片客户端  shardName => host:port
    #         shardName = "172.18.1.5:6379"




# type Client struct {
# 	ClientType          string            // 模式(normal => 单节点,cluster =>  集群,failover => 哨兵,ring => 分片)
# 	Hosts         []string          // 集群 哨兵 需要填写
# 	Password      string            // 密码
# 	Database      int               // 数据库
# 	PoolSize      int               // 连接池大小
# 	KeyPrefix     string            // 前缀标识
# 	EnableMetric bool              // 开启指标采集
# 	EnableTrace  bool              // 开启链路追踪
# 	Addr          string            // 单节点客户端
# 	Addrs         map[string]string // 分片客户端  shardName => host:port
# 	MasterName    string            // 哨兵
# }
