name: Lint Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
        id: go

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install linux deps
        run: |
            sudo apt-get update
            sudo apt-get -y install --no-install-recommends libvips-dev libvips libvips-tools

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download
          go mod graph
          go mod verify
          go mod why

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install vulnerability
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run vulnerability check
        run: govulncheck ./...